name: "Prettier Auto-Fix"
description: "Run prettier, commit any changes, and add formatting commit to .git-blame-ignore-revs"
runs:
  using: "composite"
  steps:
    - uses: planningcenter/balto-prettier@v0.2
    - uses: stefanzweifel/git-auto-commit-action@v4
      id: balto-prettier-commit
      with:
        commit_message: Formatting by balto-prettier
    - uses: ./.github/actions/append-to-file
      if: steps.balto-prettier-commit.outputs.changes_detected == 'true'
      with:
        filepath: ${{ github.workspace}}/.git-blame-ignore-revs
        contents: |-

          # balto-prettier PR #${{ github.event.number }}
          ${{ steps.balto-prettier-commit.outputs.commit_hash }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add format commit to .git-blame-ignore-revs

